# Generated by Django 2.2.4 on 2019-09-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.IntegerField(primary_key=True, serialize=False)),
                ('application_name', models.CharField(max_length=30)),
                ('application_dependency', models.CharField(max_length=200)),
            ],
        ),
    ]
