# Generated by Django 2.2.4 on 2019-09-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190901_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
