# Generated by Django 2.2.4 on 2019-09-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_operatingsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('command_id', models.AutoField(primary_key=True, serialize=False)),
                ('command_name', models.CharField(max_length=20)),
            ],
        ),
    ]
