# Generated by Django 2.2.6 on 2019-10-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='command',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='related_os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_system', to='application.OperatingSystem'),
        ),
    ]
